// Generated by: pnpm db:types
// Run `pnpm db:types` to regenerate from your Supabase project

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type Database = {
  public: {
    Tables: {
      users: {
        Row: {
          id: string
          nickname: string
          avatar_url: string | null
          bio: string | null
          safe_score: number
          swap_count: number
          is_admin: boolean
          created_at: string
        }
        Insert: {
          id: string
          nickname: string
          avatar_url?: string | null
          bio?: string | null
          safe_score?: number
          swap_count?: number
          is_admin?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          nickname?: string
          avatar_url?: string | null
          bio?: string | null
          safe_score?: number
          swap_count?: number
          is_admin?: boolean
          created_at?: string
        }
        Relationships: []
      }
      listings: {
        Row: {
          id: string
          user_id: string
          title: string
          description: string | null
          category: string
          photos: string[]
          condition: number
          price: number | null
          swap_enabled: boolean
          boost_until: string | null
          verified: boolean
          verify_tier: number
          verify_expiry: string | null
          category_meta: Json | null
          status: string
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          title: string
          description?: string | null
          category: string
          photos: string[]
          condition: number
          price?: number | null
          swap_enabled?: boolean
          boost_until?: string | null
          verified?: boolean
          verify_tier?: number
          verify_expiry?: string | null
          category_meta?: Json | null
          status?: string
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          title?: string
          description?: string | null
          category?: string
          photos?: string[]
          condition?: number
          price?: number | null
          swap_enabled?: boolean
          boost_until?: string | null
          verified?: boolean
          verify_tier?: number
          verify_expiry?: string | null
          category_meta?: Json | null
          status?: string
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "listings_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          }
        ]
      }
      proposals: {
        Row: {
          id: string
          sender_id: string
          receiver_id: string
          offered_items: string[]
          requested_items: string[]
          money_offer: number
          status: string
          escrow_id: string | null
          category_meta: Json | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          sender_id: string
          receiver_id: string
          offered_items: string[]
          requested_items: string[]
          money_offer?: number
          status?: string
          escrow_id?: string | null
          category_meta?: Json | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          sender_id?: string
          receiver_id?: string
          offered_items?: string[]
          requested_items?: string[]
          money_offer?: number
          status?: string
          escrow_id?: string | null
          category_meta?: Json | null
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      messages: {
        Row: {
          id: string
          proposal_id: string
          sender_id: string
          content: string
          blocked: boolean
          created_at: string
        }
        Insert: {
          id?: string
          proposal_id: string
          sender_id: string
          content: string
          blocked?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          proposal_id?: string
          sender_id?: string
          content?: string
          blocked?: boolean
          created_at?: string
        }
        Relationships: []
      }
      reviews: {
        Row: {
          id: string
          proposal_id: string
          reviewee_id: string
          reviewer_id: string
          rating: number
          comment: string | null
          created_at: string
        }
        Insert: {
          id?: string
          proposal_id: string
          reviewee_id: string
          reviewer_id: string
          rating: number
          comment?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          proposal_id?: string
          reviewee_id?: string
          reviewer_id?: string
          rating?: number
          comment?: string | null
          created_at?: string
        }
        Relationships: []
      }
      verifications: {
        Row: {
          id: string
          listing_id: string
          tier: number
          photos: string[]
          status: string
          reviewed_at: string | null
          expires_at: string | null
          admin_note: string | null
        }
        Insert: {
          id?: string
          listing_id: string
          tier: number
          photos: string[]
          status?: string
          reviewed_at?: string | null
          expires_at?: string | null
          admin_note?: string | null
        }
        Update: {
          id?: string
          listing_id?: string
          tier?: number
          photos?: string[]
          status?: string
          reviewed_at?: string | null
          expires_at?: string | null
          admin_note?: string | null
        }
        Relationships: []
      }
      follows: {
        Row: {
          follower_id: string
          following_id: string
        }
        Insert: {
          follower_id: string
          following_id: string
        }
        Update: {
          follower_id?: string
          following_id?: string
        }
        Relationships: []
      }
      boosts: {
        Row: {
          id: string
          listing_id: string
          user_id: string
          days: number
          amount: number
          stripe_id: string | null
          starts_at: string
          ends_at: string | null
        }
        Insert: {
          id?: string
          listing_id: string
          user_id: string
          days: number
          amount: number
          stripe_id?: string | null
          starts_at?: string
          ends_at?: string | null
        }
        Update: {
          id?: string
          listing_id?: string
          user_id?: string
          days?: number
          amount?: number
          stripe_id?: string | null
          starts_at?: string
          ends_at?: string | null
        }
        Relationships: []
      }
      notifications: {
        Row: {
          id: string
          user_id: string
          type: string
          payload: Json | null
          read: boolean
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          type: string
          payload?: Json | null
          read?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          type?: string
          payload?: Json | null
          read?: boolean
          created_at?: string
        }
        Relationships: []
      }
      categories: {
        Row: {
          id: string
          name: string
          parent_id: string | null
          icon: string
          fields: Json
          sort_order: number
          is_active: boolean
          created_at: string
        }
        Insert: {
          id: string
          name: string
          parent_id?: string | null
          icon?: string
          fields?: Json
          sort_order?: number
          is_active?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          name?: string
          parent_id?: string | null
          icon?: string
          fields?: Json
          sort_order?: number
          is_active?: boolean
          created_at?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      increment_swap_count: {
        Args: { user_id: string }
        Returns: undefined
      }
      increment_violation: {
        Args: { user_id: string }
        Returns: undefined
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}
