// Generated by: pnpm db:types
// Run `pnpm db:types` to regenerate from your Supabase project

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string
          nickname: string
          avatar_url: string | null
          bio: string | null
          safe_score: number
          swap_count: number
          is_admin: boolean
          created_at: string
        }
        Insert: {
          id: string
          nickname: string
          avatar_url?: string | null
          bio?: string | null
          safe_score?: number
          swap_count?: number
          is_admin?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          nickname?: string
          avatar_url?: string | null
          bio?: string | null
          safe_score?: number
          swap_count?: number
          is_admin?: boolean
          created_at?: string
        }
      }
      listings: {
        Row: {
          id: string
          user_id: string
          title: string
          description: string | null
          category: 'clothing' | 'skincare' | 'makeup' | 'accessories'
          photos: string[]
          condition: number
          price: number | null
          swap_enabled: boolean
          boost_until: string | null
          verified: boolean
          verify_tier: number
          verify_expiry: string | null
          category_meta: Json | null
          status: 'active' | 'swapped' | 'sold' | 'archived'
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          title: string
          description?: string | null
          category: 'clothing' | 'skincare' | 'makeup' | 'accessories'
          photos: string[]
          condition: number
          price?: number | null
          swap_enabled?: boolean
          boost_until?: string | null
          verified?: boolean
          verify_tier?: number
          verify_expiry?: string | null
          category_meta?: Json | null
          status?: 'active' | 'swapped' | 'sold' | 'archived'
          created_at?: string
        }
        Update: Partial<Database['public']['Tables']['listings']['Insert']>
      }
      proposals: {
        Row: {
          id: string
          sender_id: string
          receiver_id: string
          offered_items: string[]
          requested_items: string[]
          money_offer: number
          status: 'pending' | 'accepted' | 'declined' | 'countered' | 'completed'
          escrow_id: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          sender_id: string
          receiver_id: string
          offered_items: string[]
          requested_items: string[]
          money_offer?: number
          status?: 'pending' | 'accepted' | 'declined' | 'countered' | 'completed'
          escrow_id?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: Partial<Database['public']['Tables']['proposals']['Insert']>
      }
      messages: {
        Row: {
          id: string
          proposal_id: string
          sender_id: string
          content: string
          blocked: boolean
          created_at: string
        }
        Insert: {
          id?: string
          proposal_id: string
          sender_id: string
          content: string
          blocked?: boolean
          created_at?: string
        }
        Update: Partial<Database['public']['Tables']['messages']['Insert']>
      }
      reviews: {
        Row: {
          id: string
          proposal_id: string
          reviewee_id: string
          reviewer_id: string
          rating: number
          comment: string | null
          created_at: string
        }
        Insert: {
          id?: string
          proposal_id: string
          reviewee_id: string
          reviewer_id: string
          rating: number
          comment?: string | null
          created_at?: string
        }
        Update: Partial<Database['public']['Tables']['reviews']['Insert']>
      }
      verifications: {
        Row: {
          id: string
          listing_id: string
          tier: number
          photos: string[]
          status: 'pending' | 'approved' | 'rejected'
          reviewed_at: string | null
          expires_at: string | null
          admin_note: string | null
        }
        Insert: {
          id?: string
          listing_id: string
          tier: number
          photos: string[]
          status?: 'pending' | 'approved' | 'rejected'
          reviewed_at?: string | null
          expires_at?: string | null
          admin_note?: string | null
        }
        Update: Partial<Database['public']['Tables']['verifications']['Insert']>
      }
      follows: {
        Row: {
          follower_id: string
          following_id: string
        }
        Insert: {
          follower_id: string
          following_id: string
        }
        Update: Partial<Database['public']['Tables']['follows']['Insert']>
      }
      boosts: {
        Row: {
          id: string
          listing_id: string
          user_id: string
          days: number
          amount: number
          stripe_id: string | null
          starts_at: string
          ends_at: string | null
        }
        Insert: {
          id?: string
          listing_id: string
          user_id: string
          days: number
          amount: number
          stripe_id?: string | null
          starts_at?: string
          ends_at?: string | null
        }
        Update: Partial<Database['public']['Tables']['boosts']['Insert']>
      }
      notifications: {
        Row: {
          id: string
          user_id: string
          type: string
          payload: Json | null
          read: boolean
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          type: string
          payload?: Json | null
          read?: boolean
          created_at?: string
        }
        Update: Partial<Database['public']['Tables']['notifications']['Insert']>
      }
    }
    Functions: {
      increment_swap_count: {
        Args: { user_id: string }
        Returns: void
      }
      increment_violation: {
        Args: { user_id: string }
        Returns: void
      }
    }
  }
}
